/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vhtfcfcuvidodxjzcqcn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZodGZjZmN1dmlkb2R4anpjcWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxOTMxMDgsImV4cCI6MjA5NDc2OTEwOH0._HjHN-0Q9reE-6zrGzmG0cHaXGhBkGyegbVHweypZJA"